### ISSUE TITLE
getting errors when trying to match

### ISSUE THREAD

**Issue by daattali** [Hackout3/epimatch#1]
Data 1: CaseInformationForm.csv  
Data 2: ContactEntryForm8.csv  
Var1: Age  
Var2: ContactAge  
Matching type: gender or generic or location

With gender and generic, the error is 

```
names do not match previous names
```

With location the error is

```
non-character argument
```

Happy debugging! :tada: 

**UPDATE:** another similar bug: using CaseInformationForm.csv as the only dataset and the "Age" variable, the "gender" and "generic" functions have error

```
argument is not interpretable as logical
```

**Comment by kplaney** [comment]
Hmm…I just tried to run this with only “age” and no matches were returned.
If the same dataset is fed in (CaseInformationForm) we still get zero
matches now?

Either my new error test in collapseDistMatrices is too aggressive :) or we
actually have an error in distAges. I will test the former right now -

Warning in collapseDistMatrices(the_matrices, the_weights) :
  Distance matrix number 1 is not two-dimensional in the
collapseDistMatrices function.
Warning in collapseDistMatrices(the_matrices, the_weights) :
  No distance matrices found in collapseDistMatrices function.
Warning in is.na(names(matchIndices)) :
  is.na() applied to non-(list or vector) of type ‘NULL'


-- 
Katie Planey
https://www.linkedin.com/in/katieplaney


From:  Dean Attali <notifications@github.com>
Reply-To:  Hackout3/epimatch
<reply+00145c665acb8ff203db52c569405d620df2f6f84f8b0e0792cf00000001138571019
2a169ce09ab9459@reply.github.com>
Date:  Friday, June 24, 2016 at 3:06 PM
To:  Hackout3/epimatch <epimatch@noreply.github.com>
Subject:  [Hackout3/epimatch] getting errors when trying to match (#1)


Data 1: CaseInformationForm.csv

Data 2: ContactEntryForm8.csv

Var1: Age

Var2: ContactAge

Matching type: gender or generic or location

With gender and generic, the error is
names do not match previous names
With location the error is
non-character argument
Happy debugging! 🎉

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hackout3/epimatch/issues/1> , or mute the thread
<https://github.com/notifications/unsubscribe/ABRcZq1yXu6f-KLpFGkMTmB9eFHAiJ
L9ks5qPFUBgaJpZM4I-KZQ> .

**Comment by kplaney** [comment]
Ok fixed that :) but now getting this error that’s coming from matchGeneric
Error in if (sum(dists > 0)) { : argument is not interpretable as logical

it’s coming from line 38 – looks like a parentheses is out of place, so I
fixed it from:
if (sum(dists > 0)){
  dists <- dists/max(dists, na.rm = TRUE)
}

To:
if (sum(dists )> 0){
  dists <- dists/max(dists, na.rm = TRUE)
}

-- 
Katie Planey
https://www.linkedin.com/in/katieplaney


From:  Dean Attali <notifications@github.com>
Reply-To:  Hackout3/epimatch
<reply+00145c665acb8ff203db52c569405d620df2f6f84f8b0e0792cf00000001138571019
2a169ce09ab9459@reply.github.com>
Date:  Friday, June 24, 2016 at 3:06 PM
To:  Hackout3/epimatch <epimatch@noreply.github.com>
Subject:  [Hackout3/epimatch] getting errors when trying to match (#1)


Data 1: CaseInformationForm.csv

Data 2: ContactEntryForm8.csv

Var1: Age

Var2: ContactAge

Matching type: gender or generic or location

With gender and generic, the error is
names do not match previous names
With location the error is
non-character argument
Happy debugging! 🎉

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hackout3/epimatch/issues/1> , or mute the thread
<https://github.com/notifications/unsubscribe/ABRcZq1yXu6f-KLpFGkMTmB9eFHAiJ
L9ks5qPFUBgaJpZM4I-KZQ> .

**Comment by kplaney** [comment]
Ha I think someone already fixed that…I will stop touching matchGeneric for
now :) but it’s still giving an error for me on that line. Looks like it’s
still coming from that file, and not from the collapsing matrices step.


dat1 <- 
read.csv("~/Dropbox/github/epimatch/inst/files/CaseInformationForm.csv")
dat2 <- 
read.csv("~/Dropbox/github/epimatch/inst/files/CaseInformationForm.csv")

funlist = list(

                     names = list(d1vars = c("Gender"),
                                  d2vars = c("Gender"),
                                  fun = "genderDists",
                                  extraparams = NULL,
                                  weight = 1.0)
 )

the_matrices <- processFunctionList(dat1, dat2, funlist)
 
 Error in if (sum(dists) > 0) { : missing value where TRUE/FALSE needed

-- 
Katie Planey
https://www.linkedin.com/in/katieplaney


From:  Dean Attali <notifications@github.com>
Reply-To:  Hackout3/epimatch
<reply+00145c665acb8ff203db52c569405d620df2f6f84f8b0e0792cf00000001138571019
2a169ce09ab9459@reply.github.com>
Date:  Friday, June 24, 2016 at 3:06 PM
To:  Hackout3/epimatch <epimatch@noreply.github.com>
Subject:  [Hackout3/epimatch] getting errors when trying to match (#1)


Data 1: CaseInformationForm.csv

Data 2: ContactEntryForm8.csv

Var1: Age

Var2: ContactAge

Matching type: gender or generic or location

With gender and generic, the error is
names do not match previous names
With location the error is
non-character argument
Happy debugging! 🎉

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hackout3/epimatch/issues/1> , or mute the thread
<https://github.com/notifications/unsubscribe/ABRcZq1yXu6f-KLpFGkMTmB9eFHAiJ
L9ks5qPFUBgaJpZM4I-KZQ> .

**Comment by zkamvar** [comment]
I'll open a new issue for that. I know how to fix it.

**Comment by zkamvar** [comment]
Fixed issue with generic (and by proxy gender):

```r
indata <- system.file("files", package = "epimatch")
indata <- dir(indata, full.names = TRUE)
x <- lapply(indata, read.csv, stringsAsFactors = FALSE)
names(x) <- basename(indata)
# We will use one data set from the case information and lab results
case <- x[["CaseInformationForm.csv"]]
cont <- x[["ContactEntryForm8.csv"]]

funlist = list(

                     names = list(d1vars = c("Age"),
                                  d2vars = c("ContactAge"),
                                  fun = "genericDists",
                                  extraparams = NULL,
                                  weight = 1.0)
 )

the_matrices <- processFunctionList(case, cont, funlist)
```
